import os

LOG_LEVEL = os.getenv("LOG_LEVEL", "")
JOB_NAME = os.getenv("JOB_NAME", "")
APP_NAME = os.getenv("APP_NAME", "")
PROJECT_ID = os.getenv("PROJECT_ID", "")
STAGING_LOCATION = os.getenv("STAGING_LOCATION", "")
TEMP_LOCATION = os.getenv("TEMP_LOCATION", "")
REGION = os.getenv("REGION", "")
PUBSUB_SUBSCRIPTIONS = os.getenv("PUBSUB_SUBSCRIPTIONS", "")
GOOGLE_APPLICATION_CREDENTIALS = os.getenv("GOOGLE_APPLICATION_CREDENTIALS", "")
